name: wbl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  encrypt: ^5.0.3
  file_picker: ^8.1.7
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  mysql1: ^0.20.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_charts: ^29.1.40
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/

    
