name: wbl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  intl: ^0.20.1
  syncfusion_flutter_charts: ^28.1.38
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/

    
